version: '3.8'
services:
  web:
    build: .
    ports:
      - "5173:5173"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
